apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-mobilenet
spec:
  shutdownAfterJobFinishes: false
  entrypoint: |
    python mobilenet-imagenet/job.py
  runtimeEnvYAML: |
    pip:
      - pandas
    working_dir: "https://github.com/nasim-samimi/kuberay-test/archive/refs/heads/main.zip"

  # rayClusterSpec specifies the RayCluster instance to be created by the RayJob controller.
  rayClusterSpec:
    rayVersion: '2.9.0'
    headGroupSpec:
      rayStartParams: {}
      # Pod template
      template:
        spec:
          containers:
            - name: ray-head
              image: nasimm/mobilenet-serve:latest
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "1"
                  memory: "1500Mi"
                requests:
                  cpu: "1"
                  memory: "1500Mi"
              env:
                - name: RESPONSE_TIME_PATH
                  value: "/tmp/response_times.csv"
              volumeMounts:
                - name: response-time-volume
                  mountPath: /tmp  # Mount hostPath volume to /tmp in the container
          volumes:
            - name: response-time-volume
              hostPath:
                path: /home/master/ray  # Path on the host node
                type: DirectoryOrCreate
    workerGroupSpecs:
      - replicas: 2
        minReplicas: 1
        maxReplicas: 10
        groupName: small-group
        rayStartParams: {}
        # Pod template
        template:
          spec:
            resourceClaims:
            - name: rtcpu
              source:
                resourceClaimTemplateName: rt.example.com
            containers:
              - name: ray-worker
                image: nasimm/mobilenet-serve:latest
                resources:
                  limits:
                    cpu: "500m"
                    memory: "2Gi"
                  requests:
                    cpu: "500m"
                    memory: "2Gi"
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: rt.example.com
spec:
  spec:
    resourceClassName: rt.example.com
    parametersRef:
      apiGroup: rt.resource.example.com
      kind: RtClaimParameters
      name: rtclaims

---

apiVersion: rt.resource.example.com/v1alpha1
kind: RtClaimParameters
metadata:
  name: rtclaims
spec:
  count: 1
  runtime: 900
  period: 1000