apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-mobilenet
spec:
  shutdownAfterJobFinishes: false
  entrypoint: python mobilenet-imagenet/job.py
  runtimeEnvYAML: |
    #pip:
    #  - torch
    #  - torchvision
    #  - numpy
    working_dir: "https://github.com/nasim-samimi/kuberay-test/archive/refs/heads/main.zip"
    env_vars:
      NUM_WORKERS: "2"
      CPUS_PER_WORKER: "2"

  # rayClusterSpec specifies the RayCluster instance to be created by the RayJob controller.
  rayClusterSpec:
    rayVersion: '2.9.0'
    headGroupSpec:
      rayStartParams: {}
      # Pod template
      template:
        spec:
          containers:
            - name: ray-head
              image: nasimm/mobilenet-serve:latest
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "1"
                  memory: "4Gi"
                requests:
                  cpu: "1"
                  memory: "4Gi"
    workerGroupSpecs:
      - replicas: 4
        minReplicas: 1
        maxReplicas: 5
        groupName: small-group
        rayStartParams: {}
        # Pod template
        template:
          spec:
            containers:
              - name: ray-worker
                image: nasimm/mobilenet-serve:latest
                resources:
                  limits:
                    cpu: "500m"
                    memory: "4Gi"
                  requests:
                    cpu: "500m"
                    memory: "4Gi"
